Change graphql libs
byteleaf/companyon-backend pull request #15
Opened 2021-01-04 14:24 UTC by simon-ittmann

2021-01-04 14:57 UTC, sauterle-byteleaf commented on src/main/kotlin/de/byteleaf/companyon/common/auth/OAuth2JwtAuthenticationConverter.kt
> +// TODO implement Test
```suggestion
```
Keine TODO Kommentare im Code. -> Jira Item

2021-01-04 15:03 UTC, sauterle-byteleaf commented on src/main/kotlin/de/byteleaf/companyon/common/configuration/ModelMapperConfiguration.kt
> +                .isFieldMatchingEnabled = true // TODO remove this option -> can make problems
```suggestion
                .isFieldMatchingEnabled = true

```

2021-01-04 15:03 UTC, sauterle-byteleaf commented on src/main/kotlin/de/byteleaf/companyon/common/configuration/OAuth2ResourceServerConfiguration.kt
> +        // TODO change graphql to /** ??
```suggestion
```

2021-01-04 15:04 UTC, sauterle-byteleaf commented on src/main/kotlin/de/byteleaf/companyon/common/configuration/OAuth2ResourceServerConfiguration.kt
> +        // TODO change graphql to /** ??
Entweder abändern oder so lassen, aber kein TODO

2021-01-04 15:07 UTC, sauterle-byteleaf commented on src/main/kotlin/de/byteleaf/companyon/common/control/AbstractDataService.kt
> +        entity.id = id // make sure the url id will be used!
Und dann? Wenn die ID von der URL anders ist als das im Objekt stimmt etwas nicht.
Es sollte wenn dann geprüft werden ob beide IDs gleich sind.

2021-01-04 15:08 UTC, sauterle-byteleaf commented on src/main/kotlin/de/byteleaf/companyon/common/control/AbstractDataService.kt
> +        entity.id = id // make sure the url id will be used!
Und denn Kommentar weg :P

2021-01-04 15:10 UTC, sauterle-byteleaf commented on src/main/kotlin/de/byteleaf/companyon/common/control/AbstractEventDataService.kt
> +        // TODO add filter for roles & rights
```suggestion

```

2021-01-04 15:11 UTC, sauterle-byteleaf commented on src/main/kotlin/de/byteleaf/companyon/common/control/AbstractEventDataService.kt
> +    private var eventEmitter: Emitter<U>? = null
```suggestion
    private val lateinit eventEmitter: Emitter<U>
```

2021-01-04 15:12 UTC, sauterle-byteleaf commented on src/main/kotlin/de/byteleaf/companyon/common/control/AbstractEventDataService.kt
> +    private var eventPublisher: Flowable<U>? = null
```suggestion
       private val lateinit  eventPublisher: Flowable<U>

```

2021-01-04 15:12 UTC, sauterle-byteleaf commented on src/main/kotlin/de/byteleaf/companyon/common/control/AbstractEventDataService.kt
> +        return eventPublisher!!
```suggestion
        return eventPublisher

```

2021-01-04 15:14 UTC, sauterle-byteleaf commented on src/main/kotlin/de/byteleaf/companyon/common/control/AbstractEventDataService.kt
> +            @Suppress("UNCHECKED_CAST")
Hmmm glaube man sollte statt as -> is nehmen dann muss man das auch nicht supressen

2021-01-04 15:15 UTC, sauterle-byteleaf commented on src/main/kotlin/de/byteleaf/companyon/common/control/AbstractEventDataService.kt
> +            updatedEntity.entity = event.entity as O
```suggestion
            if (event.entity !is String) return
            updatedEntity.entity = event.entity

```

2021-01-04 15:16 UTC, sauterle-byteleaf commented on src/main/kotlin/de/byteleaf/companyon/common/dto/EntityUpdateType.kt
> +            for (entry in EntityUpdateType.values()) {
Warum nicht funktional?

2021-01-04 15:27 UTC, sauterle-byteleaf commented on src/main/kotlin/de/byteleaf/companyon/common/dto/EntityUpdateType.kt
> +            for (entry in EntityUpdateType.values()) {
EntityUpdateType.values().find{ it.eventtype == targetEventType}

EntityUpdateType.values().find{ it.eventType == targetEventType} ?: throw RuntimeException("No matching EntityUpdateType found for this event")

2021-01-04 15:32 UTC, sauterle-byteleaf commented on src/main/kotlin/de/byteleaf/companyon/user/boundary/UserResolver.kt
> +//
Auskommentierter Code entfernen

2021-01-04 15:32 UTC, sauterle-byteleaf commented on src/main/kotlin/de/byteleaf/companyon/user/control/SecurityService.kt
> +            // TODO convert to graphql error
```suggestion

```

2021-01-04 15:33 UTC, sauterle-byteleaf commented on src/main/kotlin/de/byteleaf/companyon/user/control/UserService.kt
> +        // TODO What happens if the user data changes ? how to keep this call up to date ;)
```suggestion
 ```

2021-01-04 15:34 UTC, sauterle-byteleaf commented on src/main/kotlin/de/byteleaf/companyon/user/dto/input/UserInput.kt
> +        val signature: FileMetaInput? = null,
Wieso null?

2021-01-04 15:35 UTC, sauterle-byteleaf commented on src/main/resources/banner-byteleaf.txt
> + __               __           ___                       ___
Nicht byteleaf sondern companyon

2021-01-04 15:36 UTC, sauterle-byteleaf commented on src/test/kotlin/de/byteleaf/companyon/AbstractIT.kt
> +
```suggestion

```

2021-01-04 15:37 UTC, sauterle-byteleaf requested changes
Bitte beheben ;)

2021-01-04 15:49 UTC, ptolstoi requested changes

2021-01-04 15:49 UTC, ptolstoi commented on src/main/kotlin/de/byteleaf/companyon/common/util/GenericSupportUtil.kt
>       * @param genericPosition the position of the generic, the (default) is 0
there is not default (anymore)

2021-01-04 15:49 UTC, ptolstoi commented on src/main/kotlin/de/byteleaf/companyon/user/boundary/UserResolver.kt
> +//
I'm not a fan of code, that is commented out, just remove it.

2021-01-04 15:49 UTC, ptolstoi commented on src/main/resources/application.properties
> +graphql.servlet.corsEnabled=false
I wouldn't disable CORS.

2021-01-04 15:49 UTC, ptolstoi commented on src/main/resources/graphql.schema/mutation.graphqls
> +    #    createUser(input: UserInput!): User!
I would remove the code instead of commenting it out

2021-01-04 16:40 UTC, simon-ittmann commented on src/main/kotlin/de/byteleaf/companyon/common/control/AbstractDataService.kt
> +        entity.id = id // make sure the url id will be used!
da hört man gleich die ARS Apitektenschule raus :P

2021-01-04 17:02 UTC, simon-ittmann commented on src/main/kotlin/de/byteleaf/companyon/common/control/AbstractEventDataService.kt
> +    private var eventPublisher: Flowable<U>? = null
geht leider nicht anders

2021-01-04 17:04 UTC, simon-ittmann commented on src/main/kotlin/de/byteleaf/companyon/common/control/AbstractEventDataService.kt
> +            @Suppress("UNCHECKED_CAST")
geht nur mit as, soll ja ein typecast sein

2021-01-04 17:18 UTC, simon-ittmann commented on src/main/kotlin/de/byteleaf/companyon/user/dto/input/UserInput.kt
> +        val signature: FileMetaInput? = null,
optionaler constructor parameter, muss nicht gesetzt werden

2021-01-04 17:35 UTC, simon-ittmann commented on src/main/resources/application.properties
> +graphql.servlet.corsEnabled=false
is it working with cors enabled?

2021-01-04 17:40 UTC, simon-ittmann commented on src/main/resources/application.properties
> +graphql.servlet.corsEnabled=false
seems to work ;) I tried it

2021-01-05 10:16 UTC, ptolstoi submitted a review, later dismissed

2021-01-05 11:34 UTC, sauterle-byteleaf submitted a review, later dismissed

2021-01-05 12:43 UTC, sauterle-byteleaf approved these changes

2021-01-05 12:48 UTC, merged