User domain & Authentication
byteleaf/companyon-backend pull request #20
Opened 2021-01-08 17:00 UTC by simon-ittmann

2021-01-11 12:33 UTC, ptolstoi requested changes

2021-01-11 12:33 UTC, ptolstoi commented on src/main/kotlin/de/byteleaf/companyon/user/control/UserService.kt
> +        val entity = repository.findByEmailIgnoreCase(email) ?: throw UsernameNotFoundException("No user found for email address: $email")
I would avoid leaking to much information (e.g. this email is (not) used), since an attacker could abuse it, to check which emails are in the database. I would also remove the specific email, from the error message.

2021-01-11 12:33 UTC, ptolstoi commented on src/main/resources/application.properties
> +# application constants
does it make sense to move non-sec configuration to its own configuration file?

2021-01-11 12:33 UTC, ptolstoi commented on src/test/kotlin/de/byteleaf/companyon/security/converter/JwtMock.kt
> +class JwtMock(val subjectMock: String): Jwt("a", null, null, mapOf(Pair("a", "b")), mapOf(Pair("a", "b"))) {
can you add a comment why you choose the magic values (a, two maps of a:b), or can you change the values to be more descriptive?

2021-01-11 13:00 UTC, simon-ittmann commented on src/main/resources/application.properties
> +# application constants
I think not now, but if there are several different propertie sin the futures it would make sence

2021-01-11 13:39 UTC, ptolstoi approved these changes

2021-01-12 09:11 UTC, ptolstoi approved these changes

2021-01-12 09:22 UTC, merged